[package]
name = "egomoose/deque"
description = "https://github.com/EgoMoose/deque-luau"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"